name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      
      - name: Build Site
        run: npm run build
      
      - name: Start HTTP Server (background)
        run: npx http-server dist -p 3000 &
        
      - name: Wait for server to start
        run: sleep 2
      
      - name: Run Basic Tests (Required to Pass)
        run: npx playwright test tests/basic.spec.js
        env:
          BASE_URL: http://localhost:3000
          
      - name: Run Comprehensive Tests (May Fail)
        run: npx playwright test tests/complex
        continue-on-error: true
        env:
          BASE_URL: http://localhost:3000
        env:
          BASE_URL: http://localhost:3000
          CI: true
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            test-results/
            playwright-report/
          retention-days: 30
