name: Development Build

on:
  push:
    branches-ignore: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run development build
      run: npm run dev
      
    - name: Check build output
      run: |
        echo "Build completed successfully!"
        ls -la dist/
        echo "Manifest contents:"
        cat dist/manifest.json
